-- MySQL Script generated by MySQL Workbench
-- Τρι 23 Μαρ 2021 12:25:25 πμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_1` ;
USE `exercise_1` ;

-- -----------------------------------------------------
-- Table `exercise_1`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospital` (
  `name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Telephone` INT NULL,
  PRIMARY KEY (`name`, `City`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Doctor` (
  `name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Specialization` VARCHAR(45) NULL,
  `Telephone` INT NOT NULL,
  `Hospital_name1` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_name1` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_name1` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Patient` (
  `name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Telephone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `History` TEXT(1000) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Patient_has_Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Patient_has_Hospital` (
  `Patient_email` VARCHAR(45) NOT NULL,
  `Hospital_name` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Patient_email`, `Hospital_name`, `Hospital_City`),
  INDEX `fk_Patient_has_Hospital_Hospital1_idx` (`Hospital_name` ASC, `Hospital_City` ASC) VISIBLE,
  INDEX `fk_Patient_has_Hospital_Patient_idx` (`Patient_email` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_has_Hospital_Patient`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Hospital_Hospital1`
    FOREIGN KEY (`Hospital_name` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
