-- MySQL Script generated by MySQL Workbench
-- Τρι 23 Μαρ 2021 11:28:10 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_1` ;
USE `exercise_1` ;

-- -----------------------------------------------------
-- Table `exercise_1`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospital` (
  `name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Telephone` INT NULL,
  PRIMARY KEY (`name`, `City`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Doctor` (
  `name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Specialization` VARCHAR(45) NULL,
  `Telephone` INT NOT NULL,
  `Hospital_name1` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_name1` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_name1` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Patient` (
  `name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Telephone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `History` TEXT(1000) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Visited`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Visited` (
  `Num` INT NOT NULL,
  `Date` DATE NULL,
  `Doctor_Telephone` INT NOT NULL,
  `Patient_email` VARCHAR(45) NOT NULL,
  `Hospital_name` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Num`),
  INDEX `fk_Visited_Doctor1_idx` (`Doctor_Telephone` ASC) VISIBLE,
  INDEX `fk_Visited_Patient1_idx` (`Patient_email` ASC) VISIBLE,
  INDEX `fk_Visited_Hospital1_idx` (`Hospital_name` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_Visited_Doctor1`
    FOREIGN KEY (`Doctor_Telephone`)
    REFERENCES `exercise_1`.`Doctor` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_Patient1`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_Hospital1`
    FOREIGN KEY (`Hospital_name` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Test` (
  `Type` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `Visited_Num` INT NOT NULL,
  PRIMARY KEY (`Visited_Num`),
  CONSTRAINT `fk_Test_Visited1`
    FOREIGN KEY (`Visited_Num`)
    REFERENCES `exercise_1`.`Visited` (`Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HospitalWard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HospitalWard` (
  `Id_Ward` VARCHAR(45) NOT NULL,
  `Number_rooms` INT NOT NULL,
  `Hospital_name` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Ward`),
  INDEX `fk_HospitalWard_Hospital1_idx` (`Hospital_name` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_HospitalWard_Hospital1`
    FOREIGN KEY (`Hospital_name` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Rooms` (
  `Room_id` VARCHAR(45) NOT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `Beds` INT NOT NULL,
  PRIMARY KEY (`Room_id`, `HospitalWard_Id_Ward`),
  INDEX `fk_Rooms_HospitalWard1_idx` (`HospitalWard_Id_Ward` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospitalization` (
  `hospitalization` TINYINT(1) NULL,
  `Symptoms` TEXT(150) NULL,
  `hospitalization` TEXT(200) NULL,
  `Test_Visited_Num` INT NOT NULL,
  `Rooms_Room_id` VARCHAR(45) NOT NULL,
  `Rooms_HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Test_Visited_Num`),
  INDEX `fk_Hospitalization_Rooms1_idx` (`Rooms_Room_id` ASC, `Rooms_HospitalWard_Id_Ward` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalization_Test1`
    FOREIGN KEY (`Test_Visited_Num`)
    REFERENCES `exercise_1`.`Test` (`Visited_Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospitalization_Rooms1`
    FOREIGN KEY (`Rooms_Room_id` , `Rooms_HospitalWard_Id_Ward`)
    REFERENCES `exercise_1`.`Rooms` (`Room_id` , `HospitalWard_Id_Ward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Suspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Suspect` (
  `email` VARCHAR(45) NOT NULL,
  `Test_Visited_Num` INT NOT NULL,
  PRIMARY KEY (`Test_Visited_Num`),
  CONSTRAINT `fk_Suspect_Test1`
    FOREIGN KEY (`Test_Visited_Num`)
    REFERENCES `exercise_1`.`Test` (`Visited_Num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
