-- MySQL Script generated by MySQL Workbench
-- Κυρ 28 Μαρ 2021 04:55:47 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercise_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercise_1` ;
USE `exercise_1` ;

-- -----------------------------------------------------
-- Table `exercise_1`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospital` (
  `name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Telephone` INT NOT NULL,
  `VACCIEN` TINYINT(1) NOT NULL,
  PRIMARY KEY (`name`, `City`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Doctor` (
  `Telephone` INT NOT NULL,
  `Hospital_name1` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Last_name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_name1` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_name1` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Patient` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Telephone` INT NOT NULL,
  `History` TEXT(1000) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Visited`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Visited` (
  `Num_Visited_Patient` INT NOT NULL,
  `Hospital_name` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  `Patient_email` VARCHAR(45) NOT NULL,
  `Date` DATE NULL,
  `Doctor_Telephone` INT NOT NULL,
  PRIMARY KEY (`Num_Visited_Patient`, `Hospital_name`, `Hospital_City`, `Patient_email`),
  INDEX `fk_Visited_Hospital1_idx` (`Hospital_name` ASC, `Hospital_City` ASC) VISIBLE,
  INDEX `fk_Visited_Patient1_idx` (`Patient_email` ASC) VISIBLE,
  CONSTRAINT `fk_Visited_Hospital1`
    FOREIGN KEY (`Hospital_name` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_Patient1`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`EODY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`EODY` (
  `Id-test` INT NOT NULL,
  PRIMARY KEY (`Id-test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Test` (
  `Type` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `Visited_Num_Visited_Patient` INT NOT NULL,
  `Visited_Hospital_name` VARCHAR(45) NOT NULL,
  `Visited_Hospital_City` VARCHAR(45) NOT NULL,
  `Visited_Patient_email` VARCHAR(45) NOT NULL,
  `Supect_Email` TEXT(1000) NULL,
  `EODY_Id-test` INT NOT NULL,
  PRIMARY KEY (`Visited_Num_Visited_Patient`, `Visited_Hospital_name`, `Visited_Hospital_City`, `Visited_Patient_email`),
  INDEX `fk_Test_EODY1_idx` (`EODY_Id-test` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Visited1`
    FOREIGN KEY (`Visited_Num_Visited_Patient` , `Visited_Hospital_name` , `Visited_Hospital_City` , `Visited_Patient_email`)
    REFERENCES `exercise_1`.`Visited` (`Num_Visited_Patient` , `Hospital_name` , `Hospital_City` , `Patient_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_EODY1`
    FOREIGN KEY (`EODY_Id-test`)
    REFERENCES `exercise_1`.`EODY` (`Id-test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HospitalWard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HospitalWard` (
  `Id_Ward` VARCHAR(45) NOT NULL,
  `Hospital_name` VARCHAR(45) NOT NULL,
  `Hospital_City` VARCHAR(45) NOT NULL,
  `Number_rooms` INT NOT NULL,
  PRIMARY KEY (`Id_Ward`, `Hospital_name`, `Hospital_City`),
  INDEX `fk_HospitalWard_Hospital1_idx` (`Hospital_name` ASC, `Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_HospitalWard_Hospital1`
    FOREIGN KEY (`Hospital_name` , `Hospital_City`)
    REFERENCES `exercise_1`.`Hospital` (`name` , `City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Rooms` (
  `Room_id` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_name` VARCHAR(45) NOT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_City` VARCHAR(45) NOT NULL,
  `Beds` INT NOT NULL,
  PRIMARY KEY (`Room_id`, `HospitalWard_Hospital_name`, `HospitalWard_Id_Ward`, `HospitalWard_Hospital_City`),
  INDEX `fk_Rooms_HospitalWard1_idx` (`HospitalWard_Hospital_name` ASC, `HospitalWard_Id_Ward` ASC, `HospitalWard_Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Hospital_name` , `HospitalWard_Id_Ward` , `HospitalWard_Hospital_City`)
    REFERENCES `exercise_1`.`HospitalWard` (`Hospital_name` , `Id_Ward` , `Hospital_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Hospitalization` (
  `Test_Visited_Num_Visited_Patient` INT NOT NULL,
  `Test_Visited_Hospital_name` VARCHAR(45) NOT NULL,
  `Test_Visited_Hospital_City` VARCHAR(45) NOT NULL,
  `Test_Visited_Patient_email` VARCHAR(45) NOT NULL,
  `Symptoms` TEXT(150) NULL,
  `hospitalization` TINYINT(1) NULL,
  `Treatment` TEXT(200) NULL,
  `Rooms_Room_id` VARCHAR(45) NOT NULL,
  `Rooms_HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Test_Visited_Num_Visited_Patient`, `Test_Visited_Hospital_name`, `Test_Visited_Hospital_City`, `Test_Visited_Patient_email`),
  INDEX `fk_Hospitalization_Rooms1_idx` (`Rooms_Room_id` ASC, `Rooms_HospitalWard_Id_Ward` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalization_Test1`
    FOREIGN KEY (`Test_Visited_Num_Visited_Patient` , `Test_Visited_Hospital_name` , `Test_Visited_Hospital_City` , `Test_Visited_Patient_email`)
    REFERENCES `exercise_1`.`Test` (`Visited_Num_Visited_Patient` , `Visited_Hospital_name` , `Visited_Hospital_City` , `Visited_Patient_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospitalization_Rooms1`
    FOREIGN KEY (`Rooms_Room_id` , `Rooms_HospitalWard_Id_Ward`)
    REFERENCES `exercise_1`.`Rooms` (`Room_id` , `HospitalWard_Id_Ward`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`TypeWard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`TypeWard` (
  `Type` VARCHAR(45) NOT NULL,
  `Medical_Specialty` VARCHAR(45) NULL,
  `Num_Bed` INT NULL,
  `Num_Patient` INT NULL,
  `Covid` TINYINT(1) NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_name` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HospitalWard_Id_Ward`, `HospitalWard_Hospital_name`, `HospitalWard_Hospital_City`),
  CONSTRAINT `fk_TypeWard_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward` , `HospitalWard_Hospital_name` , `HospitalWard_Hospital_City`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward` , `Hospital_name` , `Hospital_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`WorkDay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`WorkDay` (
  `Day` VARCHAR(45) NOT NULL,
  `Doctor_Telephone` INT NOT NULL,
  `HospitalWard_Id_Ward` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_name` VARCHAR(45) NOT NULL,
  `HospitalWard_Hospital_City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Doctor_Telephone`, `Day`),
  INDEX `fk_WorkDay_HospitalWard1_idx` (`HospitalWard_Id_Ward` ASC, `HospitalWard_Hospital_name` ASC, `HospitalWard_Hospital_City` ASC) VISIBLE,
  CONSTRAINT `fk_WorkDay_Doctor1`
    FOREIGN KEY (`Doctor_Telephone`)
    REFERENCES `exercise_1`.`Doctor` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WorkDay_HospitalWard1`
    FOREIGN KEY (`HospitalWard_Id_Ward` , `HospitalWard_Hospital_name` , `HospitalWard_Hospital_City`)
    REFERENCES `exercise_1`.`HospitalWard` (`Id_Ward` , `Hospital_name` , `Hospital_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HealthCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HealthCenter` (
  `Telephone` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `VACCIEN` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Telephone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Visited_HealthCenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Visited_HealthCenter` (
  `Num_Visted_Patient` INT NOT NULL,
  `Patient_email` VARCHAR(45) NOT NULL,
  `HealthCenter_Telephone` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Num_Visted_Patient`, `Patient_email`, `HealthCenter_Telephone`),
  INDEX `fk_Visited_HealthCenter_Patient1_idx` (`Patient_email` ASC) VISIBLE,
  INDEX `fk_Visited_HealthCenter_HealthCenter1_idx` (`HealthCenter_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Visited_HealthCenter_Patient1`
    FOREIGN KEY (`Patient_email`)
    REFERENCES `exercise_1`.`Patient` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visited_HealthCenter_HealthCenter1`
    FOREIGN KEY (`HealthCenter_Telephone`)
    REFERENCES `exercise_1`.`HealthCenter` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Test_Health_Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Test_Health_Center` (
  `Type` VARCHAR(45) NOT NULL,
  `Result` VARCHAR(45) NOT NULL,
  `Suspect_Email` TEXT(1000) NULL,
  `Visited_HealthCenter_Num_Visted_Patient` INT NOT NULL,
  `Visited_HealthCenter_Patient_email` VARCHAR(45) NOT NULL,
  `Visited_HealthCenter_HealthCenter_Telephone` VARCHAR(45) NOT NULL,
  `EODY_Id-test` INT NOT NULL,
  PRIMARY KEY (`Visited_HealthCenter_Num_Visted_Patient`, `Visited_HealthCenter_Patient_email`, `Visited_HealthCenter_HealthCenter_Telephone`),
  INDEX `fk_Test_Health_Center_EODY1_idx` (`EODY_Id-test` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Health_Center_Visited_HealthCenter1`
    FOREIGN KEY (`Visited_HealthCenter_Num_Visted_Patient` , `Visited_HealthCenter_Patient_email` , `Visited_HealthCenter_HealthCenter_Telephone`)
    REFERENCES `exercise_1`.`Visited_HealthCenter` (`Num_Visted_Patient` , `Patient_email` , `HealthCenter_Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_Health_Center_EODY1`
    FOREIGN KEY (`EODY_Id-test`)
    REFERENCES `exercise_1`.`EODY` (`Id-test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`HDIKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`HDIKA` (
  `AMKA` INT NOT NULL,
  `BirthDay` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AMKA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`EMA_Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`EMA_Vaccines` (
  `EMA_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Doses` INT NOT NULL,
  `Approval` TINYINT(1) NOT NULL,
  `Id_Approval` INT NULL,
  `Date_Approval` DATE NULL,
  PRIMARY KEY (`EMA_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`PharmaceuticalCorporation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`PharmaceuticalCorporation` (
  `Telephone` VARCHAR(45) NOT NULL,
  `EMA_Vaccines_EMA_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Technology` VARCHAR(45) NOT NULL,
  `Storage_Conditions` TEXT(750) NOT NULL,
  `Monthly_Production` INT NOT NULL,
  PRIMARY KEY (`Telephone`),
  INDEX `fk_PharmaceuticalCorporation_EMA_Vaccines1_idx` (`EMA_Vaccines_EMA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PharmaceuticalCorporation_EMA_Vaccines1`
    FOREIGN KEY (`EMA_Vaccines_EMA_ID`)
    REFERENCES `exercise_1`.`EMA_Vaccines` (`EMA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`StorageCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`StorageCompanies` (
  `Telephone` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercise_1`.`Batch_Of_Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercise_1`.`Batch_Of_Vaccines` (
  `PharmaceuticalCorporation_Telephone` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Number` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `vaccination centers` TEXT(1500) NOT NULL,
  `StorageCompanies_Telephone` INT NOT NULL,
  PRIMARY KEY (`PharmaceuticalCorporation_Telephone`, `Date`, `Number`, `Country`),
  INDEX `fk_Batch_Of_Vaccines_StorageCompanies1_idx` (`StorageCompanies_Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Batch_Of_Vaccines_PharmaceuticalCorporation1`
    FOREIGN KEY (`PharmaceuticalCorporation_Telephone`)
    REFERENCES `exercise_1`.`PharmaceuticalCorporation` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Batch_Of_Vaccines_StorageCompanies1`
    FOREIGN KEY (`StorageCompanies_Telephone`)
    REFERENCES `exercise_1`.`StorageCompanies` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
